In [1]:
import numpy as np

In [19]:
a = np.random.randn(3, 4)

In [20]:
b = np.random.randn(4, 2)

In [47]:
out = a.dot(b)

In [48]:
out

array([[-1.39541016,  1.30089262],
       [-0.20668377,  1.92807838],
       [ 3.0919831 ,  1.32906919]])

In [49]:
def quantize_mat(arr, percentile=0):
    low, high = np.percentile(a, percentile), np.percentile(a, 100 - percentile)
    mat_range = high - low
    uint8_mat = np.round((arr - low) * 255 / mat_range).astype(np.uint8)
    offset = -int(round(low * 255/ mat_range))
    return uint8_mat, mat_range, offset

In [74]:
def uint8_matmul(a, a_offset, a_range, b, b_offset, b_range):
    a_ = a.astype(np.int32)
    b_ = b.astype(np.int32)
    a_ += a_offset
    b_ += b_offset
    c = a_.dot(b_).astype(np.float32)
    c *= a_range * b_range / 255 / 255
    return c
    

In [67]:
a_q, a_range, a_offset = quantize_mat(a)
b_q, b_range, b_offset = quantize_mat(b)

In [68]:
a_offset

89

In [69]:
a_q

array([[ 82, 157,  23, 179],
       [120, 230,   0, 104],
       [255, 138,  73,  41]], dtype=uint8)

In [70]:
b_offset

89

In [71]:
b_q

array([[173, 121],
       [ 83, 104],
       [110,  16],
       [ 39,  99]], dtype=uint8)

In [78]:
matmul_res = uint8_matmul(a_q, -a_offset, a_range, b_q, -b_offset, b_range)

In [79]:
out

array([[-1.39541016,  1.30089262],
       [-0.20668377,  1.92807838],
       [ 3.0919831 ,  1.32906919]])

In [80]:
mat_res

array([[143706, 145532],
       [152041, 151086],
       [178050, 157501]], dtype=int32)